config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", :registrations => "my_registrations" }


  resources :posts do
  	member do
  		put "like" => "posts#upvote"
  		put "dislike" => "posts#downvote"
  	end
  end
  get 'home/index'
  root 'home#index'
  get '/got' => 'got_home#index', as: 'got'
  get '/twd' => 'twd_home#index', as: 'twd'
  get '/robot' => 'robot#index', as: 'robot'
  get '/vikings' => 'vikings#index', as: 'vikings'
  get '/extras' => 'extras#index', as: 'extras'
  get '/dashboard' => 'dashboard#index', as: 'dashboard'
  resources :contacts, only: [:new, :create]
  get '/premios' => 'premios#index', as: 'premios'


  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base

  
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,      :validate => true
  attribute :name,      :validate => true
  attribute :username,      :captche => true

  	def headers 
		  {
		  	:subject => "Juego de teorias",
		  	:to => "ezequiel.r26@gmail.com",
		  	:from => %("#{name}" <#{email}>)

		  } 
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
	  extend FriendlyId
  	friendly_id :title, use: :slugged

  	acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	
    	user.provider  = auth.provider
  		user.uid = auth.uid
  		user.username = auth.info.name
  		user.email = auth.info.email
      user.skip_confirmation!
      end
  end

  def self.new_with_session(params, session)
  	if session["devise.user_attributes"]
  		new(session["devise.user_attributes"], without_protection: true) do |user|
  			user.attributes = params
  			user.valid?
  		end
    else
  		super
  	end
  end

  def password_required?
  	super && provider.blank?	
  end

  def update_with_password(params, *options)
  	if encrypted_password.blank?
  		update_attributes(params, *options)
  	else
  		super
  	end
  end

end
 

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'No se puso enviar el mensaje'
			render :new
		end
	end
end

app/controllers/extras_controller.rb
class ExtrasController < ApplicationController
	def index
	@posts = Post.where(id_serie: 5).order("created_at DESC")
	end
end

app/controllers/got_home_controller.rb
class GotHomeController < ApplicationController
def index
	@posts = Post.where(id_serie: 1).order("created_at DESC")
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
	@posts = Post.all.limit(30).order("updated_at desc")
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate, :except => [:index, :show, :upvote, :downvote ]

	def index
	end

	def new
		@post = Post.new
	end

	def show
	end

	
	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Salvado! sos groso"
		else
			render 'new', notice: "Oh no! Hubo un error no se pudo grabar"
		end		
	end	


	def edit
	end

	def update
		if @post.update post_params
			reward_user
			redirect_to @post, notice: "Actualizado!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	#upvote from user
	def upvote
		if current_user.voted_down_on? @post
			@post.upvote_from current_user
		else
			@post.upvote_from current_user
			

			if @post.vote_registered?
				puntos = current_user.points + 100
				current_user.update_attributes(:points => puntos)
			end
		end	
		redirect_to post_path
	end

	def downvote

	if current_user.voted_up_on? @post
		@post.downvote_from current_user
	else
		@post.downvote_from current_user

		if @post.vote_registered?
			puntos = current_user.points + 100
			current_user.update_attributes(:points => puntos)
		end
	end
		redirect_to post_path
	end

private

def post_params
	params.require(:post).permit(:title, :content, :id_serie, :id_status, :id_type, :slug, :img, :written_by, :desc_serie, :points, :confirmar)
end

def find_post
	@post = Post.friendly.find(params[:id])
end

def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "usuarioadmin" && password == "ameliemlp"
     end
end

def reward_user
	
	if @post.id_status == 2 && @post.confirmar == 2
		users = @post.votes_for.up.by_type(User).voters
		puntos = @post.points

		users.each do |user|
			new_points = user.points + puntos
			User.find(user.id).update( points: new_points)
			UserNotifier.send_notification_confirmation(user, @post).deliver 

		end

	elsif @post.id_status == 3 && @post.confirmar == 2

		users = @post.votes_for.down.by_type(User).voters
		puntos = @post.points

		users.each do |user|
			if user.points != nil
			new_points = user.points + puntos
			User.find(user.id).update( points: new_points)
			UserNotifier.send_notification_rejected(user, @post).deliver  
			end
		end	 	 
	end
end
end

app/controllers/premios_controller.rb
class PremiosController < ApplicationController
	def index
	end
end

app/controllers/robot_controller.rb
class RobotController < ApplicationController
	def index
	@posts = Post.where(id_serie: 3).order("created_at DESC")
	end
end

app/controllers/vikings_controller.rb
class VikingsController < ApplicationController
	def index
	@posts = Post.where(id_serie: 4).order("created_at DESC")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/helpers/got_home_helper.rb
module GotHomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/premios_helper.rb
module PremiosHelper
end

app/helpers/robot_helper.rb
module RobotHelper
end

app/helpers/twd_home_helper.rb
module TwdHomeHelper
end

app/helpers/vikings_helper.rb
module VikingsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {

this.page.identifier = <%= @post.id %>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable

this.page.url = "<%= url_for([@post, {only_path: false}]) %>";

this.language = "es_AR";
};



(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//juegodeteorias.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form_new.html.erb
<div class="container well">

<%= form_for @post do |f|%>
	<% if @post.errors.any? %>
	<h2><%= pluralize(@post.errors.count, "error") %> prevented this form from saving: </h2>
	<ul>
		<% @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title, :class => "form-control" %>
	</p>

	<p>
		<%= f.label "Imagen ej> logo.jpg" %><br />
		<%= f.text_field :img, :class => "form-control" %>
	</p>


	<p>
		<%= f.label :id_serie%><br />
		<%= f.select(:id_serie, options_for_select([["got",1], ["twd",2], ["mr robot",3], ["Vikings",4], ["Extras",5]])) %>
	</p>

	<p>
		<%= f.label "Nombre de la serie" %><br />
		<%= f.select(:desc_serie, options_for_select([["got","Game of Thrones"], ["twd","The Walking Dead"], ["mr robot","Mr. Robot"], ["Vikings","Vikings"], ["Extras",""]])) %>
	</p>

	<p>
		<%= f.label :content %><br />
		<%= f.text_area :content, :class => "form-control", :rows => "20" %>
	</p>

	<p>
	<%= f.label "Estado"%><br />
		<%= f.select(:id_status, options_for_select([["A CONFIRMAR",1], ["CONFIRMADO",2], ["RECHAZADO",3], ["NONE",4]])) %>
	</p>
	<p>
		<%= f.label "Escrito por" %><br />
		<%= f.text_field :written_by, :class => "form-control" %>
	</p>

	<p>
		<%= f.label "Tipo del post"%><br />
		<%= f.select(:id_type, options_for_select([["Review",1], ["Teoria",2]])) %>
	</p>

	<p>
		<%= f.label "Puntos"%><br />
		<%= f.number_field :points, :class => "form-control" %>
	</p>

	<p>
		<%= f.label "Enviar mail puntos - cerrar post"%><br />
		<%= f.select(:confirmar, options_for_select([["Falso",1], ["Verdadero",2]])) %>
	</p>

	<p>
		<%= f.submit "Create new post" %>
	</p>
<% end %>

</div>

app/views/posts/edit.html.erb
<%= render 'form_new' %> 

<%= button_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/posts/new.html.erb
<h1>New</h1>

<%= render 'form_new' %> 

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-2 show_div">

<div class="status_div">
	<% if @post.id_status == 1%>
	<p class="nopadding status a_conf"> A CONFIRMAR</p>
	<% elsif @post.id_status == 2 %>
	<p class="nopadding status green"> CONFIRMADO</p>
	<%elsif @post.id_status == 3%>
	<p class="nopadding status red"> RECHAZADO</p>
	<%else%>
	<p class="nopadding status">REVIEW</p>
	<% end %>
</div>	

<p><%= l @post.created_at, :format => "%Y-%m-%d" %></p>
<h1 class="center-title"><%= @post.title %></h1>

	<div class="content-div">
	   <%= raw (@post.content) %>
	   <% if @post.points != nil %>
	   <p>Puntos:  <%= @post.points %></p>
	   <%end%>
	</div>
<div class="vote">
<% if user_signed_in? %>

<% if @post.id_status == 1 %>
<table class='center-table'>
	<tr>
		<td>
	<%= link_to like_post_path(@post), method: :put do %>
	 <i class="fa fa-arrow-up green" aria-hidden="true"><%=@post.get_upvotes.size%></i>
	<%end%>
		</td>
		<td>
	<%= link_to dislike_post_path(@post), method: :put do %>
	 <i class="fa fa-arrow-down red" aria-hidden="true"><%= @post.get_downvotes.size%></i>
	<%end%>
		</td>
	</tr>
</table>

<% elsif @post.id_status == 2 || @post.id_status == 3  %>

	<table class='center-table'>
		<tr>
			<td>
		 <i class="fa fa-arrow-up green" aria-hidden="true"><%=@post.get_upvotes.size%></i>
			</td>
			<td>
		 <i class="fa fa-arrow-down red" aria-hidden="true"><%= @post.get_downvotes.size%></i>
			</td>
		</tr>
	</table>

<% end %>


<% else %>

	<h2 class="center-title"><%= link_to "Ingresa", new_user_session_path %> ahora para votar!</h2>

<% end %>
</div>

<div class="links">
	<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @juegode_teorias - &amp;url=<%= url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
		<i class="fa fa-twitter"></i></a>

	<a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>

	<a onclick="javascript:window.open('http://plus.google.com/share?url=<%= url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>


</div>
</div>
<%= render 'disqus' %>